# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d0756ce6da534241951f419e096df0f5e837b462bce70d2765eff6cc81a07391b83e726e70878e6aae0392c07bed7e490a815ee16e44796e8a8121547f1bf1a6

test:
  secret_key_base: 7086d8efae8f0f2e24e0852e31da8a1e6fff31711629943d09f7c51bc7818cbc9f14d1e89b893e9c4d140b14662e370f15319707f8ec4f8651ea4b6b901db5a4


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= require 'securerandom'; SecureRandom.hex(64) %>
